### ISSUE TITLE
Unicode Rendering in urxvt

### ISSUE THREAD

**Issue by npreiber** [a-schaefers/i3-wm-gruvbox-theme#3]
Not an issue with your git, just asking for some advice, because you appear to solved the prolem. I can't get unicode characters to render in urxvt. For example the red, yellow and green arrow in my terminal are just boxes. You seem to have solved the problem. Could you advise me? I can't seem to find an answer anywhere.

**Comment by a-schaefers** [comment]
Hi, this is a random guess, you probably need to install more fonts. I would install a half-dozen or so more unicode fonts, restart the computer / Xorg and see what that does for you. If not, I don't know, I actually do not use urxvt anymore. (due to laziness really, it is still my favorite terminal) You might try asking around some various channels in IRC #freenode / your distro.

**Comment by a-schaefers** [comment]
rxvt-unicode also has font width settings, it is possible the package your distro uses may have default settings where the font spacing is too narrow or may have certain patches applied to display certain wide(r) unicode characters. In that case, easy fix, look up the urxvt setting for font spacing, try some numbers out in your ~/.Xresources file, xrdb ~/.Xresources and then close / open your terminal to refresh it. It is well documented online.

**Comment by npreiber** [comment]
I fixed the issue. I had actually typed the font name incorrectly lol. Thanks so much for your help though. 
I'm having a weird issue now where the bmp font that I'm using is rendered smaller in the terminal emulators than in any other application.

**Comment by a-schaefers** [comment]
That would do it. The bmp font size variations across applications that you describe I have seen also. I believe it is normal. Don't pull your hair out over it, just adjust the font sizes to compensate.

**Comment by npreiber** [comment]
The issue is that it's intolerably tiny, and others appear to be able to scale it up somehow without pixelating it. I'm assumig it must have to do with some kind of native dpi setting.

**Comment by a-schaefers** [comment]
Yes, for example I have seen openbox does this scaling it up, in my experience, but gtk with lxappearance does it also, but differently. It can be maddening to try and find one unifying font for _everything_. I suggest to use a nice xft font like Hack or Ubuntu or Noto Sans for everything and keep a super sharp bmp font  like gohufont for your terminal. That's my favorite approach.

**Comment by a-schaefers** [comment]
Anyways, you can also change things by twiddling fontconfig symlinks, I know there is also one to disable bmp font scaling. Cheers and good luck
